### ISSUE TITLE
Can't change kernel to GRUB

### ISSUE THREAD

**Issue by ababra** [btobolaski/terraform-provider-linode#10]
I tried changing the kernel field from "Latest 64 bit" to "pv-grub-x86_64" (GRUB bootloader), however I received the following:
````
* linode_linode.docker: 1 error(s) occurred:

* linode_linode.docker: Failed to create config for linode 3090847 because API Error: Invalid KernelID, Code 8
````
I also tried using the corresponding kernel ID (95) instead of "pv-grub-x86_64" with no luck - I found the name and ID by querying the Linode API. 

FYI I am trying to manage kernels on my own instead of using the Linode-provided ones and was hoping to automate it through Terraform.

**Comment by displague** [comment]
I'll have to address this in the plugin too, but the upstream may need a change as well.
https://github.com/taoh/linodego/issues/7

**Comment by displague** [comment]
The kernel you are asking for is a Xen kernel, so Linode refuses to boot that config.

The kernel you will ultimately want is "GRUB 2" or "Direct Disk".  These options don't appear in the kernel list that the plugin gets because the call is missing some API options.

**Comment by displague** [comment]
Hi @ababra! Thanks for reporting this.

This Linode provider has moved to https://www.github.com/terraform-providers/terraform-provider-linode

You will soon be able to `terraform init` the `provider "linode" {}` without needing to clone or build this repo.

Please see the docs in that repository (which will soon be hosted at https://www.terraform.io/docs/providers/linode/ )

In the official provider, you would set the kernel as:

```hcl
resource "linode_instance" {
  ...
  config {
    label = "foo"
    kernel = "linode/grub2"
    // kernel = "linode/direct-disk"
    // kernel = "linode/latest-64bit"
  }
}
```

You can find an example here:

https://github.com/terraform-providers/terraform-provider-linode/tree/master/examples
