### ISSUE TITLE
consider moving to terra-farm or core?

### ISSUE THREAD

**Issue by josephholsten** [btobolaski/terraform-provider-linode#11]
I don't know if linode is ready to start joining core, but if it is I'd like to help with the process.

If we want to not actually be in core, some folks are putting together an org like [sous-chefs](https://github.com/sous-chefs) does for chef cookbooks. Then maintainers can help each other out reviewing, merging and releasing changes. The main advantage is having more than one maintainer who can pass the torch. If that sounds interesting, the conversation is happening at https://github.com/terra-farm/meta/issues

If that doesn't sound ideal, please let me know!

**Comment by displague** [comment]
I'm working through the official https://github.com/terraform-providers/ submission process.  The intent is that https://github.com/displague/terraform-provider-linode will become 
https://github.com/terraform-providers/terraform-provider-linode.

The former is a work in progress that includes all the work from this https://github.com/btobolaski/terraform-provider-linode repository and the https://github.com/LinodeContent/terraform-provider-linode repository. 

For more info, see:
- https://www.terraform.io/docs/providers/type/cloud-index.html
- https://www.terraform.io/guides/terraform-provider-development-program.html

Thanks for the interest.

**Comment by displague** [comment]
Thanks to all the contributions and support from HashiCorp, Linode, and the community, this project has become official!

Please **Star** ⭐️ , *Watch* 👁 , and Fork 🍴 :
- https://github.com/terraform-providers/terraform-provider-linode

With this change it becomes possible to use `terraform init` to automatically install the Linode Terraform provider without the need to build and install it by hand.

The new documentation should appear at:
- https://www.terraform.io/docs/providers/linode/

Extra special thanks to @btobolaski whose [repo](https://github.com/btobolaski/terraform-provider-linode/) is the base of all this!

---


If you have been using this repo as your development base:

```sh
git remote set-url origin git@github.com:terraform-providers/terraform-provider-linode
git checkout master
git pull
```


--- 

Thanks for reporting this issue @josephholsten -- you started me on the way!
