### ISSUE TITLE
config.HelperDistro undefined

### ISSUE THREAD

**Issue by RainbowHackerHorse** [btobolaski/terraform-provider-linode#12]
`./resource_linode.go:176:44: config.HelperDistro undefined (type linodego.LinodeConfig has no field or method HelperDistro)`

I receive this error when attempting to build the plugin on FreeBSD 11 (for which you do not provide binaries).

`$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/usr/home/dashie/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build490519855=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
`

`$ go build -o terraform-provider-linode
 github.com/terraform-provider-linode
./resource_linode.go:176:44: config.HelperDistro undefined (type linodego.LinodeConfig has no field or method HelperDistro)
./resource_linode.go:178:62: config.HelperDistro undefined (type linodego.LinodeConfig has no field or method HelperDistro)`

**Comment by displague** [comment]
Hi @RainbowHackerHorse (How's it going?!), Thanks for reporting this.

This Linode provider has moved to https://www.github.com/terraform-providers/terraform-provider-linode

You will soon be able to `terraform init` the `provider "linode" {}` without needing to clone or build this repo.  I'm not sure if there will be official FreeBSD builds, but if not, please attempt a build with a modern version of Go (0.11.x) and let me if the problem has been remedied, or file an issue (and add a star ⭐️ ) at the new provider URL.

In case anyone finds this bug while trying to work with Linode config helpers in Terraform,

In the updated provider, access to the config helper attributes has moved to `linode_instance.foo.config.0.helpers.0.distro`.

Additionally, you would set them as:
```hcl
resource "linode_instance" {
  ...
  config {
    label = "foo"
    helpers {
       config = true
    }
  }
}
```

You can find an example here:

https://github.com/terraform-providers/terraform-provider-linode/tree/master/examples

Please see the docs in that repository (which will soon be hosted at https://www.terraform.io/docs/providers/linode/ ) for more details.
