### ISSUE TITLE
Regions names

### ISSUE THREAD

**Issue by jorgemfm** [btobolaski/terraform-provider-linode#15]
For anyone wonder how to get the name of the regions, you can get it here: https://www.linode.com/api/utility/avail.datacenters

This is from the old API, the new one gives different information but from what I know you cannot use it with this plugin: https://api.linode.com/v4/regions

**Comment by programingnotes** [comment]
Can anyone help with figuring out where to get information on the size and the plan? I am attempting to get the corresponding value for the smallest plan available but can't find anything on this.

**Comment by displague** [comment]
@programingnotes In this provider, the plan is specified by `size`.  The list of Linode plans are queried and the one matching the amount of RAM specified in the `size` field is chosen.

I have a gist with the Linode APIv3 Plans available here:
https://gist.github.com/displague/54d0c792ceb4716e410a772d05a13466

You can also find the plans here: https://www.linode.com/pricing (multiply 1024 by the GB of the desired plan to get the RAM `size`).

**Comment by displague** [comment]
Hi @jorgemfm, Thanks for reporting this.

This Linode provider has moved to https://www.github.com/terraform-providers/terraform-provider-linode

You will soon be able to `terraform init` the `provider "linode" {}` without needing to clone or build this repo.

Please see the docs in that repository (which will soon be hosted at https://www.terraform.io/docs/providers/linode/ )

In the updated provider, you can use a data resource to access regions and you can use the simple regions ids (`us-east`, `eu-west`, ...) in the `region` fields, just as you would in APIv4 direct calls: https://developers.linode.com/api/v4

You can find an example here:

https://github.com/terraform-providers/terraform-provider-linode/tree/master/examples
