### ISSUE TITLE
Linode Provisioner not compatible with Terraform 0.12

### ISSUE THREAD

**Issue by nigeldunn** [btobolaski/terraform-provider-linode#16]
### Terraform Version
Terraform v0.12.0

### Affected Resource(s)
The linode provisioner is not compatible with the latest version of terraform.

### Terraform Configuration Files
```hcl
provider "linode" {
  token = "my-api-token-from-linode"
}
```

### Debug Output
https://gist.github.com/nigeldunn/b6ce573dd0e5fc5a000c073327ba24f8

### Expected Behavior
Terraform to download and setup the Linode provisioner

### Actual Behavior
Terraform could not find a version of the Linode provisioner that is compatible with v0.12

### Steps to Reproduce
1. Create a main.tf file
2. Add a `provider "linode"` stanza with a linode API token
3. Run `terraform init`

**Comment by displague** [comment]
Thanks, @nigeldunn 

This repo was the original Linode provider, but it is currently just a stale fork of 
https://github.com/terraform-providers/terraform-provider-linode/

See https://github.com/terraform-providers/terraform-provider-linode/issues/50 and 
https://github.com/terraform-providers/terraform-provider-linode/pull/36

Any help from the community in getting the provider updated for 0.12 would be greatly appreciated.
