### ISSUE TITLE
Default IP address for SSH provisioners is not set

### ISSUE THREAD

**Issue by agol** [btobolaski/terraform-provider-linode#2]
Right now you need to specify the IP address for the SSH connection for the provisioners:

```
resource "linode_linode" "abc" {
    name = "abc"
    ....
    connection {
        type = "ssh"
        user = "root"
        # Does not work without the host IP below
        host = "${linode_linode.abc.ip_address}"
    }
    provisioner "file" {
        source = "script.sh"
        destination = "/tmp/script.sh"
    }
}
```

It would be great to add the default connection information at the end of `resourceLinodeLinodeRead`
https://github.com/btobolaski/terraform-provider-linode/blob/master/resource_linode.go#L187

This is done for example in the Digital Ocean provider:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L226

Azure provider:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/azure/resource_azure_instance.go#L482

You are then able to remove the whole `connection` section from the resource file.

**Comment by displague** [comment]
Hi @Agol, Thanks for reporting this.

This Linode provider has moved to https://www.github.com/terraform-providers/terraform-provider-linode

You will soon be able to `terraform init` the `provider "linode" {}` without needing to clone or build this repo.

Please see the docs in that repository (which will soon be hosted at https://www.terraform.io/docs/providers/linode/ )

In the updated provisioner, default connections work as you would expect.  You can find an example here: https://github.com/terraform-providers/terraform-provider-linode/blob/master/examples/main.tf#L156
