### ISSUE TITLE
latest binary on latest TF

### ISSUE THREAD

**Issue by adiri** [btobolaski/terraform-provider-linode#4]
running on a mac (El Capitan), this is my tf config:

```
cat ~/.terraformrc

providers {
    linode = "/usr/local/bin/terraform-provider-linode"
}
```

TF File

```
cat test.tf

provider "linode" {
  key = "xxxxxx"
}

resource "linode_linode" "foobar" {
    image = "Ubuntu 14.04 LTS"
    kernel = "Latest 64 bit"
    name = "foobaz"
    group = "integration"
    region = "Dallas, TX, USA"
    size = 1024
    status = "on"
    ssh_key =  "xxxx"
    private_networking = true
    root_password = "terraform-test"
}
```

I get this:

adir@Adirs-MacBook-Pro:~$ terraform plan tf
Error configuring: 1 error(s) occurred:

**\* Unrecognized remote plugin message: 2|unix|/var/folders/8b/k6p2ptn97xg87z55kvg_pjg80000gn/T/tf-plugin003168760**

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

**Comment by minibikini** [comment]
I get the same error.

**Comment by dshmelev** [comment]
the same

**Comment by displague** [comment]
@adiri @minibikini @dshmelev Thanks for the build feedback!

This repository has moved to https://github.com/terraform-providers/terraform-provider-linode

With this change it becomes possible to `terraform init` a `provider "linode" {}` without the need to clone and build by hand.  Please give a few days for this change to take effect.

You will also find updated documentation for this provider at
 https://www.terraform.io/docs/providers/linode

Have a look at the updated URL's `examples/` and `website/` directory to get a feel for the changes and open any new issues on that repository (and bring your Github Stars!). 

Thanks!
