### ISSUE TITLE
Unrecognized remote plugin message

### ISSUE THREAD

**Issue by lucaswxp** [btobolaski/terraform-provider-linode#6]
I get the following when running the example on terraform v0.9.3:

```
Error asking for user input: 1 error(s) occurred:

* provider.linode: Unrecognized remote plugin message: 2|unix|/var/folders/mw/y5nw62813y9105dl9n5wy6_40000gn/T/tf-plugin372053172

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

How can I fix it?

**Comment by displague** [comment]
I'll have a look later today.  I haven't encountered build version issues yet, but I'll see what I can do.

I've picked up the @btobolaski branch to get the Linode provider merged into core, incorporating @bdwyertech's #1, and have been working on adding additional Terraform Linode Resources support (Domains).  https://github.com/hashicorp/terraform/compare/master...displague:add-linode-provider?expand=1

**Comment by lucaswxp** [comment]
That's nice! Any prediction? Any way I can help debug this further? I'm no golang expert, but I can try to help.

**Comment by displague** [comment]
I'm no expert either. If this problem is blocking you, you could try
following the README to build the plugin yourself.

I'll have a better idea when I try it later, myself.

**Comment by jvrplmlmn** [comment]
@displague maybe I'm missing something but I can't find the instructions to build the plugin. Could you link them?

I'm using Terraform v0.9.2 and I'm experiencing the same issues as @lucaswxp:

```
Error importing: 1 error(s) occurred:

* provider.linode: Unrecognized remote plugin message: 2|unix|/var/folders/zw/lqcz80hj51b5q8_y56kc_1jr0000gn/T/tf-plugin093750271

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by acloudiator** [comment]
I have build using the source from here. Just in case, anyone wants to try this plugin for Terraform-v0.9.4 
https://github.com/acloudiator/terraform-provider-linode/tree/build/build/Terraform-v0.9.4

**Comment by displague** [comment]
@jvrplmlmn I see that the README.md is missing that info.  I'll have to sort it out and add something.

I have notes on how to build from the core branch I am working on: 
https://gist.github.com/displague/5497abe1c23e214cb27160d9faaa7883

**Comment by aeb0** [comment]
Same error with Terraform v0.9.11 on OSX 10.12.4
```
* provider.linode: Unrecognized remote plugin message: 2|unix|/var/folders/jg/g1g752k53knbgrz6sspnsks80000gn/T/tf-plugin315043264

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by lucaswxp** [comment]
@acloudiator For what distro have you built? I'm getting `cannot execute binary file: Exec format error`

**Comment by lucaswxp** [comment]
Hey guys.

So the easiest solution I found was to keep two terraform versions. The version that works with the linode provider is the v0.5.3, you can download it here:

https://releases.hashicorp.com/terraform/0.5.3/

**Comment by displague** [comment]
@lucaswxp @aebrow4 @jvrplmlmn Thanks for the build feedback!

This repository has moved to https://github.com/terraform-providers/terraform-provider-linode

With this change it becomes possible to `terraform init` a `provider "linode" {}` without the need to clone and build by hand.  Please give a few days for this change to take effect.

You will also find updated documentation for this provider at
 https://www.terraform.io/docs/providers/linode

Have a look at the updated URL's `examples/` and `website/` directory to get a feel for the changes and open any new issues on that repository (and bring your Github Stars!). 

Thanks!
