### ISSUE TITLE
Incorrect docs, no "status" field

### ISSUE THREAD

**Issue by ababra** [btobolaski/terraform-provider-linode#8]
The example under "Resource Configuration" states that there is a "status" field. However when running ``terraform -plan``, the following error occurs: 
````
1 error(s) occurred:

* linode_linode.docker-backup: "status": this field cannot be set
````
Omitting the field still results in the linode being powered up after plan execution. I am using Terraform v0.9.4 with the build referenced [here](https://github.com/btobolaski/terraform-provider-linode/issues/6#issuecomment-299086972)

**Comment by acloudiator** [comment]
The usage of this plugin is very limited, I don't think you can set the status field with this plugin. But more people can collaborate and enhance it.

**Comment by displague** [comment]
As the code is now, this is only a computed field, meaning you can only see the status last captured.

It should be settable, but the use-case for having a Linode in an off-state (which you must still pay for) is limited.  I suppose with careful scripting you may want to bring machines up, then down, then back up in a specific order.

**Comment by displague** [comment]
Hi @ababra and @acloudiator, thanks for working through this issue.

This repository has been moved to https://www.github.com/terraform-providers/terraform-provider-linode

The `linode_instance.*.status` values are different now, based on the [APIv4 values](https://developers.linode.com/api/v4).

It is possible to create a Linode that does not intend to boot (by not providing any Terraform `disk` or `boot_config_label` values), but it is not possible to toggle the status value to adjust the power setting.

I'm closing this issue so this repository can be archived, but please reopen this issue with more details on your use-case and how a read/write status field would benefit that work flow.

Thanks again!
